config/routes.rb
Rails.application.routes.draw do
  root to: "sessions#new"
  resources :blogs
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :index, :create, :show]
  resources :favorites, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :blog
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :blogs, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :blog
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :loggin_check

  def index
    @blogs = Blog.all
  end

  def show
    @favorite = current_user.favorites.find_by(blog_id: @blog.id)
  end

  def new
    @blog = Blog.new
  end

  def edit
  end

  def create
    @blog = current_user.blogs.build(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to blogs_path, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_blog
      @blog = Blog.find(params[:id])
    end

    def blog_params
      params.require(:blog).permit(:title, :content)
    end

    def loggin_check
      unless logged_in?
        redirect_to new_session_path
      end
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController


  def create
    favorite = current_user.favorites.create(blog_id: params[:blog_id])
    redirect_to blogs_url, notice: 'お気に入りしました！'
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to blogs_url, notice: 'お気に入り解除しました！'
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :loggin_in_check, only: [:new]

  def new; end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to blogs_path, notice: 'ログインに成功しました！'
    else
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to new_session_path
  end

  private
  def loggin_in_check
    redirect_to blogs_path if logged_in?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :loggin_in_check
  before_action :set_params, only: [:show]
  def new
    @user = User.new
  end

  def show
    @blogs = current_user.favorite_users.all
    @blogs_count = current_user.favorite_users.count
  end

  def create
    @user = User.new(params_user)
    if @user.save
      session[:user_id] = @user.id
      redirect_to blogs_path, notice: '登録に成功しました！'
    else
      render :new
    end
  end

  private
  def params_user
    params.require(:user).permit(:name,:email, :password, :password_confirmation)
  end

  def loggin_in_check
    # redirect_to blogs_path if logged_in?
  end

  def set_params
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<div class="form">
  <h1>Editing Blog</h1>

  <%= render 'form', blog: @blog %>

  <%= link_to 'Show', @blog %> |
  <%= link_to 'Back', blogs_path %>
</div>

app/views/blogs/index.html.erb
<div class="index">
  <p id="notice"><%= notice %></p>

  <h1>Blogs</h1>
  <%= current_user.name %>
  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Content</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @blogs.each do |blog| %>
        <tr>
          <td><%= blog.title %></td>
          <td><%= blog.content %></td>
          <td><%= blog.user.name %></td>
          <td><%= link_to 'Show', blog %></td>
          <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
          <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Blog', new_blog_path %>
</div>

app/views/blogs/new.html.erb
<div class="form">
  <h1>新規投稿</h1>

  <%= render 'form', blog: @blog %>

  <%= link_to 'Back', blogs_path %>
<div>

app/views/blogs/show.html.erb
<div class="form">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Title:</strong>
    <%= @blog.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= @blog.content %>
  </p>
  <% unless @blog.user_id == current_user.id %>
    <% if @favorite.present? %>
      <%= link_to 'お気に入りを削除する', favorite_path(id: @favorite.id), method: :delete %>
    <% else %>
      <%= link_to 'お気に入りする', favorites_path(blog_id: @blog.id), method: :post %>
    <% end %>
  <% end %>

  <%= link_to 'Edit', edit_blog_path(@blog) %> |
  <%= link_to 'Back', blogs_path %>
<div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WorkApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <header>
    <% if logged_in? %>
      <%= link_to "プロフィール", user_path(current_user.id) %>
      <%= link_to "ログアウト", session_path(current_user.id) ,method: :delete %>
    <% else %>
      <%= link_to "サインアップ", new_user_path %>
      <%= link_to "ログイン", new_session_path %>
    <% end %>

  </header>
  <body>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<div class="form">
  <h1>サインアップ</h1>

  <%= form_with(model: @user, local: true) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :email %>
    <%= f.email_field :email %>
    <%= f.label :password %>
    <%= f.text_field :password %>
    <%= f.label :password_confirmation %>
    <%= f.text_field :password_confirmation %>
    <%= f.submit %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="show">
  <h1>プロフィール</h1>



  <h2>お気に入り数</h2>
  <p><%= @blogs_count %></p>

  <h2>お気に入り一覧</h2>
  <table>
    <tr>
      <th>タイトル</th>
      <th>内容</th>
    </tr>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.content %></td>
      </tr>
    <% end %>
  </table>
  <%= link_to "戻る", blogs_path %>

</div>